### ISSUE TITLE
No access token after .token()

### ISSUE THREAD

**Issue by ramiel** [anvilresearch/connect-nodejs#27]
In my application I do the following
```js
client.token({code: 'aabbcc'})
  .then(function(){
    client.register({})
  })
.catch(...)
```

The token sent to the register endpoint is `Bearer undefined` because in the client->register function the token is got like this:

```js
var token = this.tokens && this.tokens.access_token
``` 

but `this.tokens` is undefined. Am I doing something wrong?

**Comment by dmitrizagidulin** [comment]
@ramiel - we've refactored the `client.token()` method on Friday, so this issue is likely to have been fixed. Can you try it again and report?

Although, on second thought, this may be a workflow misunderstanding. Can you explain your use case or what you're trying to do? From what I understand, you *first* register() a client, and then can use it to exchange the code for a token, etc.

**Comment by ramiel** [comment]
Sorry, I mean the "create" endpoint, to create a new client.
So, this is what I have to do:
- An application which run server-side receive a request
- It does his job and then it have to generate a new client on anvil
- This new client is created without the intervention of an human user so I cannot ask someone to login.

How can I do it?

**Comment by dmitrizagidulin** [comment]
Ah, right, ok. So I've actually been working on this exact same use case all last week. Let me see if I can explain the workflow...

**Comment by dmitrizagidulin** [comment]
**Step 1: Determine the Issuer.** (This determines which server you're going to be registering your client to.)
If you have just one OIDC server (anvil connect server, in this case) running, then this step is easy, just load the issuer URL from your config or whatever. So, if you're running your Anvil server on `https://oidc.example.com`, then step 1 looks like: `issuer = 'https://oidc.example.com'`.

If you have *multiple* issuers / OIDC Providers (which is the use case I'm dealing with), you have to discover the issuer from the access token (from the request object). So my code looks like:

```js
    var issuer
    try {
      issuer = client.extractIssuer(req)
    } catch (err) {
      console.log('Error during extractIssuer: ' + err)
      return next(err)
    }
```

**Step 2: Create a client (or load an existing one) for that issuer**
Because I'm dealing with multiple issuers, and because you only need one OIDC client *per* issuer, it makes sense to store or cache the clients once you create them. (I'm currently just storing them in memory, but hoping to serialize them on disk). But before you can store the client, you obviously have to create it. My code looks something like this (this is a method on an OidcRpClient class):

```js
var OIDCClient = require('anvil-connect-nodejs')
// ...
this.clientForIssuer = function clientForIssuer (issuer) {
    return this.clients.get(issuer)  // clients.get() is just a simple async fetch from memory
      .then((client) => {
        console.log('Client fetched for issuer.')
        if (client) {
          return client
        }
        console.log('Client not present, initializing new client.')
        // client not already in store, create and register it
        let clientConfig = {
          issuer: issuer,
          redirect_uri: this.redirect_uri,   // this is the redirect_uri of your app or service, loaded from config
          scope: 'openid profile'
        }
        var client = new OIDCClient(clientConfig)
        return this.initClient(client)
      })
  }
```
Let me know if you have any questions here -- so far, I'm either loading a previously created client, or just instantiating a new client and passing it an `issuer` (discovered or from config), a `redirect_uri` (from config), and a `scope` (hardcoded). And passing that instance to `initClient()`, which registers it (see below).

**Step 3: Register the client (if you created it fresh in step 2):** 
(Apologies for the ES6 `=>` syntax)

```js
  initClient (client) {
    // initProvider() calls discover() and getJWKs()
    return client.initProvider()
      .then(() => {
        console.log('Client discovered, JWKs retrieved')
        if (!client.client_id) {
          // Register if you haven't already.
          console.log('Registering client')
          return client.register(registration())
        }
      })
      .then(() => {
        console.log('Storing registered client')
        return this.clients.put(client)
      })
      .then(() => client)
      .catch((err) => { throw err })
  }
```
The only thing missing here is the `registration()` function, which builds the [`register()` options](https://github.com/anvilresearch/connect-nodejs#clientregisterregistration). Something like:

```js
function registration() {
  return {
    client_name: 'My OIDC RP Service',
    client_uri: 'https://app.example.com',
    logo_uri: 'https://app.example.com/assets/logo.png',
    response_types: ['code'],
    grant_types: ['authorization_code', 'refresh_token'],
    default_max_age: 86400, // one day in seconds
    redirect_uris: ['https://app.example.com/callback'],
    post_logout_redirect_uris: ['https://app.example.com/post-logout']
  }
}
```

Let me know if all this makes sense!

**Comment by ramiel** [comment]
I think I'm mixing the concept of:
- register a client
- create a client

I think I need more "create a new client".  In fact I'm using `client.clients.create()`

Am I wrong of thinking they are two separate concepts?

**Comment by dmitrizagidulin** [comment]
You're right, they are two separate concepts. (Stand by, will explain in a bit)

**Comment by dmitrizagidulin** [comment]
Ok, so the main challenge here is that in order to do anything useful, you have to possess a client which has been pre-registered with an issuer/Provider. (Which means, specifically, that both the client and the server have exchanged secrets and public keys etc). You can get there in one of three ways:

1. A **single client** that the developer or admin user has **pre-registered** (say, using the `nvl` commandline). Which means you can load its CLIENT_ID & CLIENT_SECRET into your app's config, and you're good to go (you can instantiate the client and pass in that info directly into the constructor). This is the most common case, and the main problem is of course -- you're limited to just one issuer/provider. The moment that other providers enter into the mix, you have to use one of the other two methods.
2. **Dynamic registration**. If you've set up your Anvil Connect server to enable dynamic registration, you can create new clients for new issuers via the process I outlined in a previous comment -- get the issuer, instantiate a client, load the issuer info via `initProvider()`, then `register()` and you're good to go.
3. Alternatively, you can **use the Anvil Connect API** (via the  `connect-nodejs` client) to create a new client by calling `client.clients.create()`. The thing to keep in mind is - the effect is the same as dynamic registration, the only difference is the mechanism (and various fine points of security and trust, which @christiansmith would be able to speak to better). But as you discovered, you need an access `token` in order to be able to do this (this makes sense, you don't want *any* old client to be able to use the back-end Anvil Connect API, which lets you create clients, users, etc etc). To get that token, you either have to:
  * 3a) Be logged in as an **admin-type user** (which gets you an ID Token / access token that you need). This is what the command-line `nvl` client does -- that's why you have to `nvl login` first before doing anything else, to get that token in the background. Specifically, this user needs to have the `authority` role added to their account (the first admin user you create when you do `nvl setup` sets this role by default). OR:
  * 3b) Use a **privileged client** (pre-registered already, from method 1), where the *client* has had an `authority` role granted to it using `nvl client:assign <CLIENT_ID> <ROLE>` (see the [client docs](https://github.com/anvilresearch/connect-docs/blob/master/clients.md)). So that's done once, during install/setup time -- you register the first (privileged) client via the command line, then grant it the authority role, and THEN you can just put its CLIENT_ID and CLIENT_SECRET into your app's config, and then instantiate it and use it to call `client.clients.create()` to create new clients.

Makes sense?

**Comment by dmitrizagidulin** [comment]
Oh, the missing bit is *how* you do 3a). Once you have a client with an `authority` role, you have to do the following:

**1) Instantiate the privileged client:**

```js
var client = new OIDCClient({ // client id, client secret, issuer })
// The first time it's created, you still need it to call initProvider(), however:
client.initProvider()
  .then(function () {  // now you're ready to get the token and create clients, see below })
```

**2) Get the token**

```js
client.token({
  grant_type: 'client_credentials',
  scope: 'realm'
})
  .then(function (tokenResponse) {
    var token = { token: tokenResponse.access_token }
    // finally, you're ready to client.clients.create()
  })
```

**Comment by ramiel** [comment]
Ok, this is very similar to what I did. Let me show you what i made and let's see if there is a better workflow. I did this before your answer so it's a bit different. So, first of all I implemented the 3a case. I created a pre-registered client with the authority role. I looked at the code of anvil-connect -cli and the code I have at the last is the following:

```js
createClient(clientData) {
        return client.initProvider()
            .then(() => {
                return client.discover();
            })
            .then(() => {
                return client.login(administrativeUserCredentials);
            })
            .then(tokens => {
                return client.clients.create(clientData, {token: tokens.access_token});
                // Passing a second parameter is btw not well documented. I don't remember where I saw it
            });
    }
```

Where `login` is implemented the same way as on anvil-connect-cli and `administrativeUserCredentials` are credentials from an administrative user saved somewhere in our application.
What I don't like about this approach is that I have to use an user to login in order to get a token.

What I actually want to do is to use a client but without the needs to have an user. So I think I should follow the 3b.
In you latest comment you explain how to implement 3a but maybe you refer to 3b because no user looks involved. So if I understood well I can use the code in you latest comment to use credential from a client without involving an user. What I do not understand is:

```js
client.token({
  grant_type: 'client_credentials',
  scope: 'realm'
})
```

I think this code works because of an OIDC flow but it's not clear where it comes from (it's my fault btw).
Another question is: Which parameters have I to use to create the client on anvil? I'm referring mostly to the `grant_types`, `application_type` and `response_types`. I think the confusion about this part is due to my lack of knowledge on OIDC/Oauth2 matter...but is a complex world in any case :)

**Comment by dmitrizagidulin** [comment]
Yeah, whoops, sorry bout that - I meant how to implement 3b in the comment above. (I just edited it to reflect that).

> I think this code works because of an OIDC flow but it's not clear where it comes from

So, from what I understand, this comes from [OAuth2 Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4) workflow. And yeah, you're absolutely right, this is a really complex stack, and you and I are kind of on the bleeding edge of what this library is doing. Hence the lack of docs etc. (I literally learned all of this stuff on Friday).

> Which parameters have I to use to create the client on anvil?

So, I'm not super clear about this part (or what your use case is exactly). But check out the [Client Properties](https://github.com/anvilresearch/connect-docs/blob/master/clients.md#client-properties) section of the docs, and ask more questions. If it helps, here are my parameters that I'm using (when registering the initial privileged client via `nvl`):

```json
{
  "redirect_uris": [
    "https://localhost:3000/api/oidc/callback"
  ],
  "response_types": [
    "code",
    "id_token token",
    "code id_token token",
    "token"
  ],
  "grant_types": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ],
  "application_type": "web",
  "client_name": "My Service",
  "client_uri": "https://localhost:8443",
  "token_endpoint_auth_method": "client_secret_basic",
  "default_max_age": 36000,
  "post_logout_redirect_uris": [],
  "trusted": true,
  "scopes": []
}
```

**Comment by dmitrizagidulin** [comment]
Oh, one other thing in your code above -- `initProvider()` calls `discover()` internally, so no need to call it again.

**Comment by ramiel** [comment]
Thank you! I'll say more to you tomorrow.

**Comment by ramiel** [comment]
Interesting discussion btw. I hope someone can take advantage of this thread too.

**Comment by dmitrizagidulin** [comment]
Thanks! (Yeah, I definitely think some of this stuff should make it into this repo's README etc)

**Comment by ramiel** [comment]
I implemented the 3b) flow. I have a client like this:
```js
{
  "redirect_uris": [
    "http://localhost:8000/"
  ],
  "response_types": [
    "id_token token"
  ],
  "grant_types": [
    "implicit"
  ],
  "application_type": "service",
  "client_name": "Shop admin",
  "logo_uri": "http://localhost:8000/imgages/logo-uri.png",
  "client_uri": "http://localhost:8000",
  "token_endpoint_auth_method": "client_secret_basic",
  "default_max_age": 3600,
  "post_logout_redirect_uris": [
    "http://localhost:8000"
  ],
  "client_secret": "d7df6acaf3a797026ec7",
  "trusted": true,
  "scopes": [],
  "_id": "2912c173-6d3a-4be3-b76b-4225a38a01d9",
  "created": 1463063700064,
  "modified": 1463499699138
}
```

with the role `authority`.
I'm able to create a new client using this one. What is strange is that the `client_credentials` is not defined in the grant_types. I thought it was mandatory in order to do
```js
client.token({grant_type: 'client_credentials', scope: 'realm'})
```
to obtain an access token.

**Comment by dmitrizagidulin** [comment]
I see. I think (and @christiansmith can correct me on this) that the `grant_types` in the client properties has to do with -- those are gonna be the default grant types that your tokens will have. Or something like that. So, unrelated to the `client.token()` invocation.
